---
SEED:
  seed: 0

MODEL:
  gamma: 1.0
  learning_rate: 0.05
  max_depth: 5
  reg_lambda: 5.0
  scale_pos_weight: 100
  tree_method: 'gpu_hist'
  objective: 'binary:logistic'
  use_label_encoder: False
  missing: Null
  seed: 0
  eval_metric: 'auc'
